//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;  

[assembly: System.Reflection.AssemblyCompanyAttribute("TokenParser")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("TokenParser")]
[assembly: System.Reflection.AssemblyTitleAttribute("TokenParser")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0")]


[assembly: InternalsVisibleTo("Test.TokenParser") ]  
// 由 MSBuild WriteCodeFragment 类生成。

