name: create publish key
on: [push]
jobs:
  create_key:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    steps:
      - name: create
        run: cd ./MathParser && dotnet nuget add source --username zyxia --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"