name: "Publish"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
        
        
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion
      - name: Set tag to version  
        run: cd ./MathParser/MathParser && dotnet TagToVersion -t ${{github.ref}} 
      - name: Install dependencies
        run: dotnet restore ./MathParser/MathParser.sln   
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:        
          nuget-version: '5.x'
      - name: pack
        run: cd ./MathParser/MathParser && dotnet pack MathParser.csproj --configuration Release
      - name: Add private GitHub registry to NuGet
        run:  dotnet nuget add source --username zyxia --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/zyxia/index.json"
      - name: Push generated package to GitHub registry
        run:  cd ./MathParser/MathParser && ls && nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate && nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -apikey ${{secrets.NugetKey}} -NoSymbols 